### PR TITLE
Adding ApplicationNavigation w/ Workspace integration

### PR DESCRIPTION
**Pull request by tbiethman**
### Summary

With this PR, the ApplicationNavigation component implementation has been moved to the terra-application package. The Workspace has been integrated into the ApplicationNavigation's API to allow for presentation there.

### Deployment Link

https://terra-applic-.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by mjhenkes — APPROVED** [review]

**Review by benbcai — APPROVED** [review]

**Comment by scottwilmarth** [comment]
Adding my plus one for accessibility of skip to links and providing context of moving focus.

**Comment by ryanthemanuel** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please include a CHANGELOG entry for each changed package on this PR. Looks like a CHANGELOG is missing for: 

 - terra-dev-site</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c6584838965c8847401e5746c753913de0106173
</p>

**Comment by sethbroox** [comment]
Reviewed visual changes to Enterprise and LowLight Themes.
+1 from UX

**Review by ryanthemanuel — APPROVED** [review]

**Comment by mjhenkes** [comment]
Hooray 🎉🥳

**Pull request merged**
