### PR TITLE
Updated eslint config terra dependency

### LINKED ISSUE #42: Update eslint-config-terra v3.0.0 to @cerner/eslint-config-terra v^4.0.0
# Feature Request

## Description
Update the existing dependency and eslint config to the latest version of the new scoped package.

### PR DESCRIPTION
**Pull request by DMcginn**
### Summary
Updated the eslint-config-terra dependency from v^3.0.0 to @cerner/eslint-config-terra v^4.0.0, along with the associated config.

Closes #42 

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
Are we able to clean up any disabled rules with this latest version? You should be able to check with:
```
npm run lint:js -- --report-unused-disable-directives 
```

**Comment by DMcginn** [comment]
@emilyrohrbough I removed all the unused rules with [aa49334](https://github.com/cerner/terra-application/pull/43/commits/aa49334bc68884b920ed4fc891112e0e74a15014). Is this something I need to add to the change log?

**Comment by emilyrohrbough** [comment]
Yeah you will need to add to the changelog..It's not really something "changelog" worthy IMO but there isn't a way to distinguish that in our changelog checks so the build will fail if you don't add changelog entries

**Review by emilyrohrbough — APPROVED** [review]

**Review by BenBoersma — APPROVED** [review]

**Comment by DMcginn** [comment]
Snapshots for Application Navigation had to be updated due to changes made by PR [1146 in terra-framework](https://github.com/cerner/terra-framework/pull/1146). These updated snapshots should ensure that the relevant WDIO tests pass correctly [6d92ff1](https://github.com/cerner/terra-application/pull/43/commits/6d92ff132aaa8149af243357dead75935e1fe292).

**Review by mjhenkes — APPROVED** [review]

**Pull request merged**
