### PR TITLE
Update browserslist-config-terra to @cerner/browserslist-config-terra

### LINKED ISSUE #64: Update browserslist-config-terra v1.2.0 to @cerner/browserslist-config-terra v^3.0.0
# Feature Request

## Description
We recently updated our browserslist config & released it as a scoped package. We should move to the latest version.

### PR DESCRIPTION
**Pull request by lokesh-0813**
### Summary

Closes #64 

### Deployment Link

https://terra-applic-.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

**Review by avinashg1994 — APPROVED** [review]

**Comment by avinashg1994** [comment]
@lokesh-0813, Can you add a Changelog entry for this update.

**Review by StephenEsser — CHANGES_REQUESTED** [review]
Adding a temporary request changes to prevent merging.

Before moving forward with these changes we'd like to investigate on any impact this may have downstream. There have been a few reports that might indicate these changes causing issues during webpack. 

A good test to determine if this is the case would be to install terra-application into a project using the previous browserlist-config-terra (dependency and extends), start the webpack dev server, verify the application starts successfully and then clean installing a snapshot version of terra-application that has been upgraded to use @browserlist-config-terra and performing the same webpack test, but keeping the previous browserlist-config-terra dependency and extends in the project installing terra-application. 

Note: This may be related to dependencies installed via git references 

Edit:

I've done some initial investigation using the steps above and seeing webpack failures.

Steps:

1. Clone https://github.com/StephenEsser/browserslist-spike
2. Run `npm install`
3. Run `npm start`
4. Observe the terminal output.

Terminal Output:

https://gist.github.com/StephenEsser/108a127c05150d2e003fb011a41634f2

These steps were done using a git referenced and a file reference to a packed .tgz file with the same outcome.

**Comment by emilyrohrbough** [comment]
@lokesh-0813  have you done any investigation around the issue Stephen found?

**Comment by lokesh-0813** [comment]
> @lokesh-0813 have you done any investigation around the issue Stephen found?

@emilyrohrbough I tried to build Stephen's project and it was throwing a bunch of errors unrelated to the original issue(could be due to windows machine wrongly configured). I'm having a device swap tomorrow and will start investigating it. 

Also @ryanthemanuel pointed out this will be closed for now. But he did ask me to investigate it, so I will start over once I have the new device.

**Comment by StephenEsser** [comment]
@lokesh-0813 

It's probably a windows incompatibility issue with the file paths being used in the webpack config:

https://github.com/StephenEsser/browserslist-spike/blob/master/webpack.config.js

Let me know if you run into issues on the new device, alternatively these paths can be updated locally to run on windows

**Comment by lokesh-0813** [comment]
@StephenEsser I was looking into this and you were right. I am getting the same error as you. 

What I noticed is, 
1. If I change `browserslist-config-terra` to `@cerner/browserslist-config-terra` [here](https://github.com/StephenEsser/browserslist-spike/blob/master/package.json#L27), I don't get any errors with the snapshot version of terra-application.

2. Also `Terra-application v.1.34.0` complains about missing `browserslist-config-terra`. I am not sure why and I am looking into it. I will update this PR once I have more.

**Comment by emilyrohrbough** [comment]
What happens if you add the old browserslist config to the sample project in the package.json? Is the issue because no browserlist config is defined when it's expected for wepback / babel?

**Comment by lokesh-0813** [comment]
@emilyrohrbough It expects same version as terra-application.

If terra-application has `browserslist-config-terra`, it expects `browserslist-config-terra`. 

If terra-application has `@cerner/browserslist-config-terra`, it expects `@cerner/browserslist-config-terra`.

> What happens if you add the old browserslist config to the sample project in the package.json?

Its looking for `@cerner/browserslist-config-terra`.

**Comment by emilyrohrbough** [comment]
@lokesh-0813 are you okay with we close this PR and re-open once we've determined what / how / if this can be resolved? We can move any conversation to the issue?

**Comment by lokesh-0813** [comment]
Hey @emilyrohrbough , yes you can close it for now. I will update the issue on my findings.

**Comment by StephenEsser** [comment]
Closing this PR while investigation is ongoing

**Pull request closed without merging**
